baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "STAT 564 Fall 20187"
theme = "material"
#disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeurls = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Shen Qu"
  bio = ""
  job = "Ph.D."
  location = "Portland State University"
  gravatarEmail = "qushen@pdx.edu"
  # Your profile picture
#  picture = ""
  twitter = ""
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "syllabus"
  name = "Syllabus"
  pre = "<i class=\"material-icons\">date_range</i>"
  url = "/syllabus"
[[menu.main]]
  weight = 3
  identifier = "tools"
  name = "Tools and Datasets"
  pre = "<i class=\"material-icons\">build</i>"
  url = "/tools"
[[menu.main]]
  weight = 4
  identifier = "policies"
  name = "Policies"
  pre = "<i class=\"material-icons\">gavel</i>"
  url = "/policies"

[[menu.footer]]
  weight = 1
  identifier = "D2L"
  name = "D2L@pdx"
  pre = "<i class=\"button-icon fa fa-2x fa-map-marker\"></i>"
  url = "http://d2l.pdx.edu/"
[[menu.footer]]
  weight = 2
  identifier = "DataCamp"
  name = "DataCamp"
  pre = "<i class=\"button-icon fa fa-2x fa-pencil\"></i>"
  url = "https://www.datacamp.com/groups/usp654"
[[menu.footer]]
  weight = 3
  identifier = "Slack"
  name = "Slack"
  pre = "<i class=\"button-icon fa fa-2x fa-slack\"></i>"
  url = "https://usp634-f17.slack.com/messages"
[[menu.footer]]
  weight = 4
  identifier = "GitHub"
  name = "GitHub"
  pre = "<i class=\"button-icon fa fa-2x fa-github\"></i>"
  url = "https://github.com/usp654/"


[params]
  dateFormat = "January 2, 2006"
  background = "http://www.greggirard.com/content/gallery/GIrard_KWC_temple01.jpg"
  favicon = ""
